import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#0b1c30",
        "tertiary-container": "#5f2b00",
        "primary-fixed-dim": "#c3c0ff",
        "on-tertiary-fixed-variant": "#70380b",
        surface: "#f8f9ff",
        "on-error": "#ffffff",
        "primary-container": "#312e81",
        "on-tertiary-container": "#de915e",
        "surface-container-high": "#dce9ff",
        "on-secondary-fixed-variant": "#005236",
        tertiary: "#3e1a00",
        "surface-bright": "#f8f9ff",
        "outline-variant": "#c8c5d3",
        "surface-container": "#e5eeff",
        "secondary-fixed": "#6ffbbe",
        background: "#f8f9ff",
        secondary: "#006c49",
        "on-secondary-fixed": "#002113",
        "inverse-primary": "#c3c0ff",
        "on-primary-fixed-variant": "#3e3c8f",
        "inverse-surface": "#213145",
        "tertiary-fixed": "#ffdbc7",
        "on-secondary-container": "#00714d",
        "on-primary-container": "#9c9af4",
        "tertiary-fixed-dim": "#ffb688",
        "surface-variant": "#d3e4fe",
        outline: "#777682",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#474651",
        "primary-fixed": "#e2dfff",
        "inverse-on-surface": "#eaf1ff",
        "surface-tint": "#5654a8",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#0b1c30",
        "on-primary-fixed": "#100563",
        "surface-container-highest": "#d3e4fe",
        "secondary-fixed-dim": "#4edea3",
        "on-error-container": "#93000a",
        "surface-container-low": "#eff4ff",
        error: "#ba1a1a",
        "surface-dim": "#cbdbf5",
        primary: "#1a146b",
        "error-container": "#ffdad6",
        "secondary-container": "#6cf8bb",
        "on-tertiary-fixed": "#311300",
        "on-secondary": "#ffffff",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-xl": [
          "36px",
          { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": [
          "24px",
          {
            lineHeight: "32px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "headline-md": [
          "20px",
          { lineHeight: "28px", fontWeight: "600" },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "mono-data": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
      spacing: {
        "stack-lg": "24px",
        "stack-md": "16px",
        "stack-sm": "8px",
        gutter: "24px",
        "margin-page": "32px",
      },
    },
  },
  plugins: [],
};

export default config;
